// IPC channel names and payload types — full implementation in Phase 3

export type IpcChannel =
  // Request-response channels
  | 'db:get-user'
  | 'db:list-repos'
  | 'db:add-repo'
  | 'db:update-repo'
  | 'db:delete-repo'
  | 'db:list-workspaces'
  | 'db:get-workspace'
  | 'db:create-workspace'
  | 'db:update-workspace'
  | 'db:delete-workspace'
  | 'workflow:list'
  | 'workflow:get'
  | 'workflow:create'
  | 'workflow:update'
  | 'workflow:delete'
  | 'session:list'
  | 'session:get'
  | 'session:start'
  | 'session:pause'
  | 'session:resume'
  | 'session:delete'
  | 'agent:list'
  | 'agent:get-messages'
  | 'agent:send-input'
  | 'agent:kill'
  | 'approval:list-pending'
  | 'approval:list-pending-grouped'
  | 'approval:resolve'
  | 'decision:list'
  | 'decision:list-grouped'
  | 'decision:get'
  | 'decision:update'
  | 'decision:delete'
  | 'artifact:read'
  | 'artifact:toggle-pin'
  | 'artifact:delete'
  | 'shell:open-external'
  | 'shell:pick-folder'
  | 'window:open-spec-popout';

export type PushChannel =
  | 'agent:token'
  | 'agent:message'
  | 'agent:status-change'
  | 'agent:completed'
  | 'approval:new'
  | 'approval:resolved'
  | 'session:status-change'
  | 'phase:advanced';
